#include "ota_idf_sink.hpp"
#if CONFIG_SATORI_WIFI_OTA_PROTOTYPE
#include <cstring>
#include "esp_app_desc.h"
#include "esp_secure_boot.h"
#include "ota_board_tag.hpp"

namespace satori::ota {
namespace {
Slot SlotOf(const esp_partition_t* p) {
    if (!p||p->type!=ESP_PARTITION_TYPE_APP) return Slot::Other;
    return p->subtype==ESP_PARTITION_SUBTYPE_APP_OTA_0?Slot::Ota0:
        p->subtype==ESP_PARTITION_SUBTYPE_APP_OTA_1?Slot::Ota1:Slot::Other;
}
bool ExactSlot(const esp_partition_t* p) {
    return p&&!p->encrypted&&p->size==kSlotSize&&
        ((SlotOf(p)==Slot::Ota0&&p->address==0x10000)||
         (SlotOf(p)==Slot::Ota1&&p->address==0x180000));
}
}
bool OfficialSignaturePolicyReady() {
#if CONFIG_SECURE_SIGNED_APPS_NO_SECURE_BOOT && CONFIG_SECURE_SIGNED_ON_UPDATE_NO_SECURE_BOOT && CONFIG_SECURE_SIGNED_APPS_RSA_SCHEME && !CONFIG_SECURE_BOOT
    esp_image_sig_public_key_digests_t keys{};
    // Native C3 software mode trusts the first running-image signature block.
    // No key is installed/generated by this API and no eFuse is written.
    return esp_secure_boot_get_signature_blocks_for_running_app(true,&keys)==ESP_OK&&keys.num_digests==1;
#else
    return false; // prototype has no selected/approved authenticity policy
#endif
}
IdfOtaSink::IdfOtaSink(const ImageManifest& manifest,bool (*continue_guard)()):manifest_(manifest),continue_guard_(continue_guard) {
    running_=esp_ota_get_running_partition();update_=esp_ota_get_next_update_partition(nullptr);
    mbedtls_sha256_init(&hash_);
}
IdfOtaSink::~IdfOtaSink() { Abort();mbedtls_sha256_free(&hash_); }
Slot IdfOtaSink::running_slot() const { return SlotOf(running_); }
Slot IdfOtaSink::update_slot() const { return SlotOf(update_); }
bool IdfOtaSink::running_valid() const {
    esp_ota_img_states_t state{};
    return ExactSlot(running_)&&esp_ota_get_state_partition(running_,&state)==ESP_OK&&state==ESP_OTA_IMG_VALID;
}
bool IdfOtaSink::Begin(const Manifest& m) {
    if (attempted_) return false;
    attempted_=true;
    if ((continue_guard_&&!continue_guard_())||!OfficialSignaturePolicyReady()||!running_valid()||!ExactSlot(update_)||running_==update_||
        running_->address==update_->address||m.target_slot!=update_slot()||
        m.board!="satori_c3_v1"||m.chip!="esp32c3"||!ManifestValid(manifest_)||
        m.image_size!=manifest_.image_size||m.sha256!=manifest_.sha256) return false;
    // Version is metadata, not an ordering gate: same-version and downgrade
    // images still pass all board/signature/integrity/slot checks below.
    std::array<unsigned,3> offered{};
    if (!ParseVersion(manifest_.version,offered)) return false;
    if (mbedtls_sha256_starts(&hash_,0)!=0) return false;
    const auto rc=esp_ota_begin(update_,manifest_.image_size,&handle_);
    active_=rc==ESP_OK;return active_;
}
bool IdfOtaSink::Write(const std::uint8_t* data,std::size_t bytes) {
    if ((continue_guard_&&!continue_guard_())||!active_||!data||bytes>manifest_.image_size-written_) return false;
    if (esp_ota_write(handle_,data,bytes)!=ESP_OK||mbedtls_sha256_update(&hash_,data,bytes)!=0) return false;
    written_+=static_cast<std::uint32_t>(bytes);return true;
}
void IdfOtaSink::Abort() {
    verified_=false;
    if (active_) { active_=false;(void)esp_ota_abort(handle_);handle_=0; }
    // Inactive-slot garbage is never selected or erased again during cleanup.
}
Verification IdfOtaSink::FinishVerifyAuthenticity() {
    if ((continue_guard_&&!continue_guard_())||!active_||written_!=manifest_.image_size) return Verification::IntegrityFailure;
    std::array<unsigned char,32> hash{};
    if (mbedtls_sha256_finish(&hash_,hash.data())!=0||hash!=manifest_.sha256) return Verification::IntegrityFailure;
    // Verify stored Flash bytes independently of the received stream.
    mbedtls_sha256_context stored{};mbedtls_sha256_init(&stored);
    bool ok=mbedtls_sha256_starts(&stored,0)==0;
    std::array<unsigned char,2048> buffer{};
    for (std::uint32_t at=0;ok&&at<written_;) {
        if (continue_guard_&&!continue_guard_()) { ok=false;break; }
        const auto amount=written_-at<buffer.size()?written_-at:buffer.size();
        ok=esp_partition_read(update_,at,buffer.data(),amount)==ESP_OK&&mbedtls_sha256_update(&stored,buffer.data(),amount)==0;
        at+=amount;
    }
    ok=ok&&mbedtls_sha256_finish(&stored,hash.data())==0&&hash==manifest_.sha256;
    mbedtls_sha256_free(&stored);
    if (!ok) return Verification::IntegrityFailure;
    if (!OfficialSignaturePolicyReady()) return Verification::AuthenticityFailure;
    // Under the approved native config, esp_ota_end verifies the actual SBv2
    // RSA3072 signature against the running signed app, as well as image/chip.
    const auto rc=esp_ota_end(handle_);active_=false;handle_=0;
    if (rc!=ESP_OK) return Verification::AuthenticityFailure;
    esp_app_desc_t desc{};BoardTag tag{};
    const auto* current=esp_app_get_description();
    if (esp_partition_read(update_,kBoardTagImageOffset,&tag,sizeof(tag))!=ESP_OK||
        std::memcmp(&tag,&kExpectedBoardTag,sizeof(tag))!=0||
        esp_ota_get_partition_description(update_,&desc)!=ESP_OK||
        strnlen(desc.version,sizeof(desc.version))>=sizeof(desc.version)||
        std::string_view(desc.version)!=manifest_.version||
        std::memcmp(desc.project_name,current->project_name,sizeof(desc.project_name))!=0||
        desc.secure_version!=current->secure_version) return Verification::AuthenticityFailure;
    verified_=true;return Verification::Verified;
}
bool IdfOtaSink::SetBootTarget(Slot slot) {
    if ((continue_guard_&&!continue_guard_())||!verified_||selected_||slot!=update_slot()||!running_valid()) return false;
    if (esp_ota_set_boot_partition(update_)!=ESP_OK) return false;
    selected_=true;verified_=false;return true;
}
} // namespace satori::ota
#endif
