#pragma once
#define CONFIG_SATORI_WIFI_OTA_PROTOTYPE 1
#if TEST_NATIVE_POLICY
#define CONFIG_SECURE_SIGNED_APPS_NO_SECURE_BOOT 1
#define CONFIG_SECURE_SIGNED_ON_UPDATE_NO_SECURE_BOOT 1
#define CONFIG_SECURE_SIGNED_APPS_RSA_SCHEME 1
#define CONFIG_SECURE_BOOT 0
#endif
